title: "HERS&reg Diagnostic Output Schema"
author: "RESNET&reg"
description: "A schema for detailed diagnostic outputs from RESNET&reg Accredited HERS&reg software tools."
colors:
  primary: "indigo"
